Financial-Times/google-amp

bower.json, scss/style.scss
=> copypasta next styles for promobox/inline related article

server/controllers/amp-page.js, server/lib/render-article.js, views/article.html
=> Schema dot org

scss/style.scss
https://bugs.webkit.org/show_bug.cgi?id=82489
=> safari svg bug workaround

scss/style.scss
[![screenshot 2016-02-22 12 29 56](https://cloud.githubusercontent.com/assets/631757/13218262/29966564-d960-11e5-8461-d4fe76f1a695.png)](https://ft-google-amp-staging-pr-30.herokuapp.com/content/788c532a-ca5d-11e5-be0b-b7ece4e953a0)
[![screenshot 2016-02-22 12 30 03](https://cloud.githubusercontent.com/assets/631757/13218265/2b0d1fd2-d960-11e5-97be-e94609520f4e.png)](https://ft-google-amp-staging-pr-30.herokuapp.com/content/e9424f8a-af4f-3e08-bfa9-b561cbca37d2)
=> {pull,block}quote

server/stylesheets/blockquotes.xsl, server/stylesheets/main.xsl, views/article.html
[![screenshot 2016-02-23 12 09 24](https://cloud.githubusercontent.com/assets/631757/13251151/65c4477e-da26-11e5-9808-7c343c3474e5.png)](http://ft-google-amp-staging-pr-34.herokuapp.com/content/49ed693b-d539-3a14-9ecb-ad37d96d3f99)
There seems to be no way to centre-align the embedded tweet :confused:
=> embed tweets

package.json, scss/style.scss, server/lib/compile-scss.js
=> Add css minification

views/article.html
as per https://github.com/ampproject/amphtml/issues/2444#issuecomment-192388105
=> Ensure success param is passed

.eslintrc, fetch-svgs/.gitignore, package.json, scripts/instrument.js, server/controllers/amp-page.js, server/lib/external-images.js, server/lib/get-stream-url.js, server/lib/getArticle.js, server/lib/related-content/more-ons.js, server/lib/wrap-fetch.js
This should be totally safe in production, as the instrumentation happens at require-time and just returns the original fetch if NODE_ENV isn't `instrument`.
=> Instrument fetch

scripts/bench.sh
=> fix killing benchmark server on exit

package.json, scripts/instrument.js, server/lib/external-images.js, server/lib/get-stream-url.js, server/lib/getArticle.js, server/lib/related-content/more-ons.js, server/lib/wrap-fetch.js
I have no idea if this actually gains us anything, or if it's working for all requests :grimacing:
=> more generic fetch wrapping

server/controllers/amp-page.js
http://ft-google-amp-staging-pr-88.herokuapp.com/content/4f8a0ffe-35e9-11de-a997-00144feabdc0
=> fix 404s turning into 500s

app.js
@georgecrawford this is the missing piece to get "Resolved in next release" working
=> tag sentry errors with release

server/lib/report-error.js, server/lib/wrap-fetch.js
caused https://app.getsentry.com/nextftcom/amp/issues/117339714/
=> protect against undefined options

app.js, app.json, circle.yml, package.json, scripts/bench.sh, scripts/test.sh, server/controllers/access-mock.js, server/controllers/amp-page.js, server/lib/cheerio-transform.js, server/lib/transforms/light-signup.js
positioning as in IA. tested, seems to be working fine. i'll test tracking separately but i see no reason it wouldn't be working.
=> add light signup transform and config

scss/style.scss
=> add 'advertisement' message

app.js, app.json, server/controllers/amp-page.js, server/controllers/analytics-config.js
i have having to copy/paste the uuid every time i visit a new pull request heroku app
=> redirect root to snake people

views/article.html
=> Add explicit amp-ad script

views/ads-iframe.html
=> Change amp ad unit again

server/controllers/amp-page.js, views/article.html, views/partials/header.html, views/partials/sidebarMenu.html
not ready for merge, open questions about tracking
=> new psp url AT-425

server/lib/cors.js
(i.e. actually read the spec you're implementing, matt)
=> only check origin and source origin if origin exists

.eslintrc.json, Procfile, app.js, package.json, scripts/bench.sh, scripts/loadtest.sh, server/index.js
Including using `cluster` to spin up multiple processes on large-enough dynos
=> Better memory behaviour on heroku

server/lib/related-content/story-package.js
See https://sentry.io/nextftcom/amp/issues/117312155
=> Story package error

views/partials/barrier.html
https://ftnext.invisionapp.com/share/VG8FSFORB#/screens
=> support b2b test barrier AT-756

views/ads-iframe.html
/cc @quarterto (completely untested but looks legit)
=> Fix for potential missing api key/value

server/lib/live-blogs/get-live-blog.js
bit of a mess rn, needs refactoring
=> always register stop timeout, including on error

server/lib/transforms/insert-ad.js
cc: @quarterto @adgad @andrewgeorgiou1981 
For this JIRA ticket https://jira.ft.com/browse/ADS-1110
=> Add: 2nd ad unit after 9th para if there is one

scss/header.scss, scss/sidebar.scss, server/lib/get-css.js, server/lib/transforms/copyright-notice.js, server/stylesheets/amp-links.xsl, server/stylesheets/amp-related-box.xsl, views/partials/footer.html, views/partials/header.html, views/partials/sidebarMenu.html
Reverts Financial-Times/google-amp#185
=> Revert "Sidebar AT-35"

server/controllers/amp-page.js, server/lib/analytics.js, server/lib/article/segment.js, views/article.html
If I'd done this ticket a couple of months ago, at some point I'd have needed to go "Geoooorge, is `amp_visibility_experiment_enabled` a reasonable key?". I have no idea where to find this kind of thing out or who to ask.
=> At 881 visibility test

views/partials/barrier.html
=> change to corporate link on barrier

views/partials/barrier.html
@quarterto updated hardcoded packshot to latest version as discussed :)
=> updated pack shot url to 2017 version

app.json, package.json, scripts/selector-example.js, server/health/elastic-search.js, server/lib/article/article-flags.js, server/lib/article/assemble.js, server/lib/article/environment-options.js, server/lib/transforms/body.js, server/lib/transforms/html/unfurl-video.js, server/lib/transforms/utils/get-video.js, test/.eslintrc.json, test/amp-transform/external-image.js, test/amp-transform/unfurl-video.js, test/amp-transform/video.js, test/fixtures/56f6ad50-da52-11e5-a72f-1e7744c66818.json, test/fixtures/video/3235593137001.json, test/fixtures/video/9010a752-585c-3230-9507-9990e3361e68.json, test/integration/brightcove.js, views/layouts/layout.html
=> AT-1090 new video embeds

server/index.js
=> Unblock certain endpoints for robots

server/lib/cors.js
only accepts requests from itself
=> better testing for valid CORS origins

package-lock.json, package.json
Fixes the security warning, ~so adding back package-lock.json~.
=> Upgrade mocha to 5.2.0

makefile, scripts/dev-utils/bench.sh, scripts/dev-utils/loadtest-tools.sh
`npm run bench` should now work.
=> Fix up the npm run bench script

.bowerrc, .circleci/config.yml, .editorconfig, .gitignore, circle.yml, makefile, package-lock.json, package.json
=> CircleCI 2.0

.gitignore, package-lock.json, scss/barrier.scss, server/lib/article/article-flags.js, server/lib/cors.js, views/article.html, views/layouts/layout.html, views/partials/barrier.html, views/partials/footer.html, views/partials/header.html, views/partials/mockAccess.html, views/partials/related/more-ons.html, views/partials/related/story-package.html, views/partials/sidebarMenu.html
This partially reverts #279 but keeps the HTTPS setup so that #290 works
=> Revert swg

package-lock.json, scss/barrier.scss, server/lib/article/article-flags.js, server/lib/cors.js, views/article.html, views/layouts/layout.html, views/partials/barrier.html, views/partials/footer.html, views/partials/header.html, views/partials/mockAccess.html, views/partials/related/more-ons.html, views/partials/related/story-package.html, views/partials/sidebarMenu.html
until ampproject/amphtml#16370 is fixed
=> Revert "Revert swg"

package-lock.json, scss/barrier.scss, server/lib/article/article-flags.js, server/lib/cors.js, views/article.html, views/layouts/layout.html, views/partials/barrier.html, views/partials/footer.html, views/partials/header.html, views/partials/mockAccess.html, views/partials/related/more-ons.html, views/partials/related/story-package.html, views/partials/sidebarMenu.html
Reverts Financial-Times/google-amp#295
=> Revert "Revert "Revert swg""

package-lock.json, scss/barrier.scss, server/lib/analytics.js, server/lib/article/article-flags.js, server/lib/cors.js, views/article.html, views/layouts/layout.html, views/partials/barrier.html, views/partials/footer.html, views/partials/header.html, views/partials/mockAccess.html, views/partials/related/more-ons.html, views/partials/related/story-package.html, views/partials/sidebarMenu.html
=> Amp Subscriptions

package-lock.json, scss/barrier.scss, server/lib/analytics.js, server/lib/article/article-flags.js, server/lib/cors.js, views/article.html, views/layouts/layout.html, views/partials/barrier.html, views/partials/footer.html, views/partials/header.html, views/partials/mockAccess.html, views/partials/related/more-ons.html, views/partials/related/story-package.html, views/partials/sidebarMenu.html
=> Revert amp-subscriptions

package-lock.json, scss/barrier.scss, server/lib/analytics.js, server/lib/article/article-flags.js, server/lib/cors.js, views/article.html, views/layouts/layout.html, views/partials/barrier.html, views/partials/footer.html, views/partials/header.html, views/partials/mockAccess.html, views/partials/related/more-ons.html, views/partials/related/story-package.html, views/partials/sidebarMenu.html
Reverts Financial-Times/google-amp#308 and fixes spoor tracking data issue.
~~Only to be merged when https://github.com/ampproject/amphtml/issues/16720 is solved.~~
=> Reinstate `amp-subscriptions`

makefile, package-lock.json, package.json, views/layouts/layout.html, views/partials/barrier.html, views/partials/header.html, views/partials/sidebarMenu.html
The `subscriptions-action` property will automatically hide an element unless you provide a `subscriptions-display` property that provides rules for when it should display.
=> Fix sign in links

renovate.json
Depends on https://github.com/renovatebot/presets/pull/88.
Should group upgrades to postcss packages into a single PR.
=> Add postcss group

package.json
Reverts https://github.com/Financial-Times/google-amp/pull/338.
=> Downgrade to Node.js 8

package-lock.json, package.json
Reverts Financial-Times/google-amp#354
=> Revert "Update dependency raven to v2"

views/partials/barrier.html
=> Bump swg button to top of barrier

server/lib/transforms/html/insert-ad.js, test/amp-transform/insert-ad.js
Ads where not being targeted because the ad server was expecting a `pos` parameter in the request.
This should fix it.
=> Add missing "pos" parameter to ad requests

server/lib/analytics.js, views/layouts/layout.html
Hooking up these events that were recently added: https://github.com/ampproject/amphtml/pull/19413
=> Account linking tracking

.eslintrc.json, server/controllers/products.js, test/utils/test-uuids.js
Trello card: https://trello.com/c/IYbaVzLS/605-premium-price-increase-2019
Related PR: https://github.com/Financial-Times/next-barrier-guru/pull/309
=> Remove test priceIncrease variant offer from barrier

scss/barrier.scss, views/partials/barrier.html
| Before | After |
| --- | --- |
| ![screencapture-local-ft-5050-content-56183ac6-807a-11e9-9935-ad75bb96c849-2019-05-28-13_43_54](https://user-images.githubusercontent.com/1721150/58478740-a9571700-814e-11e9-984e-b1e44c5874b1.png) | ![screencapture-local-ft-5050-content-56183ac6-807a-11e9-9935-ad75bb96c849-2019-05-28-13_42_53](https://user-images.githubusercontent.com/1721150/58478685-93495680-814e-11e9-84b6-79134f1f95ab.png) |
=> Move SwG panel further down the barrier

views/layouts/layout.html
=> removing Krux - krux is no longer used by FT products

server/controllers/amp-page.js, server/lib/article/assemble.js
so that users coming from twitter don't see a 404 page and can read the article 🐿 v2.12.5
=> redirect skipped article instead of 404ing it

views/layouts/layout.html
png is 813 bytes and svg is 450 bytes (because we can gzip it)
=>  use an svg icon and fallback to png

server/lib/format-barrier-data.js, test/lib/format-barrier-data.spec.js, views/partials/barrier.html
Fixes link issue originated in https://github.com/Financial-Times/google-amp/pull/450
=> ACQ-502 Restored moustache mistaken for handlebars

server/lib/article/skip.js
by request from @musthemag in Slack DMs
=> Skip eastern mediterranean crisis article

server/lib/article/skip.js
I've added the UUID for a video led article that Editorial are planning to publish soon.
Original pull request: https://github.com/Financial-Times/google-amp/pull/463
=> Skip David Allen Green legislation article

.circleci/config.yml, package.json
=> Upgrade to Node v12

.gitignore, scss/_hacks.scss, scss/comments.scss, views/article.html, views/layouts/layout.html, views/partials/footer.html, views/partials/header.html, views/partials/link.html, views/partials/related/more-ons.html
This pull request fixes a few accessibility issues, this doesnt mean these pages are as accessible as they should be but does improve things.
Review commit by commit for justification for changes.
=> Fix some accessibility issues
