Financial-Times/google-amp

- server/lib/render-article.js
It's kinda cool that this worked for so long! The only key in common is actually `mainImage`, and this explains why the Google carousel listings have weird images sometimes - it's because the response from the `getMainImage()` routine was being throw away.
> Correct order for Object.assign

- scss/style.scss
- server/controllers/amp-page.js
- server/lib/get-stream-url.js
- server/lib/primary-theme.js
- server/lib/related-content/more-ons.js
- server/lib/related-content/story-package.js
- server/lib/render-article.js
- views/article.html
Clickable primary theme for articles:
and story packages:
and more-ons:
This PR also includes stream links for any authors mentioned in metadata, although currently, none of them correctly redirect to vanity URLs on FT.com, so they won't appear until that's fixed.
> Stream links

- scss/style.scss
@quarterto What d'ya think about this? It's a bit hacky, but I wanted the headline font sizes to retain a touch of proportionality even at the smallest size. This is apparent on an iPhone when viewed in the Google carousel, as there's reduced vertical viewport height. This PR means that the headline remains slightly larger than the standfirst.
> Keep font-sizes somewhat proportional even at smallest sizes

- package.json
- server/controllers/amp-page.js
- server/lib/get-stream-url.js
- server/lib/primary-theme.js
- server/lib/related-content/more-ons.js
- server/lib/related-content/story-package.js
- server/lib/render-article.js
by default, node-fetch follows redirects. ft.com immediately returns a 302 for stream pages that exist, so node-fetch redirects and loads the actual topic page.
> don't follow redirects in get-stream-url

- package.json
- server/lib/get-stream-url.js
- server/lib/getArticle.js
- server/lib/related-content/story-package.js
- server/lib/wrap-fetch.js
@georgecrawford this does a good job of showing why some `get-stream-urls` start later: they're caused by the storypackage getarticle requests (which we knew already, but it's good to see it)
> group related instrumented fetches (i.e storypackage)

- app.js
Currently you get a different version depending on if you hit US or EU
> RELEASE_VERSION is not consistent across apps

- scss/style.scss
@quarterto @georgecrawford 
Hiya - I'm fixing calls to the build service in next and noticed this. 
`https://h2.ft.com/build/files/o-fonts-assets@1.3.0/MetricWeb-Light.woff`
will get a 404, but 
`https://h2.ft.com/build/v2/files/o-fonts-assets@1.3.0/MetricWeb-Light.woff`
should work.
> eliminate obs redirect

- scripts/test-uuids.sh
- server/stylesheets/interactive-graphics.xsl
- views/article.html
This applies to interactive graphics that are displayed using iframes.
If the graphic source is insecure then we have to simply remove it. For
graphics which are served over HTTPS, we create an amp-iframe.
There's currently no way to test HTTPS iframes automatically, IG was
unable to find an article which used them. Regardless, this is an
improvement on the current behaviour for any existing articles which
have iframe-embedded interactive graphics.
> Output interactive graphics in valid AMP HTML

- app.json
- server/lib/get-stream-url.js
I've set `VERIFY_STREAM_URLS = false` on this review app only, so we can see how this behaves in staging. Note that we should wait for fixed AWS keys before testing and releasing this.
> Only check stream URLs when required by env

- views/ads-iframe.html
Values that are booleans get skipped out of the ad call, so convert them to strings.
@quarterto @VladDubrovskis
> Convert targeting param to string

- scss/abTest.scss
- scss/style.scss
- server/controllers/analytics-config.js
- views/article.html
- views/partials/abTest.html
Points of interest:
- currently set to 'non-sticky', so user will receive a new bucket for each visit. 'sticky' is probably what we want for our tests
- Any remainder from the bucket % total is assigned to 'none' in analytics
- tracked as: `user.ab.background-color-test: "yellow"`, etc
- force a particular bucket by appending `#amp-x-background-color-test=yellow` to the URL
> Commented-out but working AB test code

- scss/style.scss
> Fix margin on slideshow title

- server/lib/cheerio-transform.js
- server/lib/report-error.js
- server/lib/transforms/link-analytics.js
- server/lib/transforms/remove-invalid-links.js
1. Sanitise text values, so that `<a ... data-vars-link-text="one device for " convenience""="">one device for "convenience"</a>` becomes `<a ... data-vars-link-text="one device for convenience">one device for "convenience"</a>`
2. Remove links with empty `href` or an invalid protocol (as per https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii)
> AT-627: Fix some Google search console errors

- .gitignore
- makefile
- package.json
- scripts/jira-release-issues.js
- scripts/version.sh
@timdavenportFT this sets the CR summary to `Release google-amp XXX.0.0-heroku-abcdef1` and the description to the output of `heroku pipelines:diff`, which looks like:
```
=== ft-google-amp-staging is ahead of ft-google-amp-prod-us by 5 commits
SHA      Date                  Author        Message
───────  ────────────────────  ────────────  ───────────────────────────────────────────────────
36b8781  2016-11-07T16:31:20Z  Matt Brennan  Merge pull request #191 from Financial-Times/readme
1ec583d  2016-11-07T16:30:39Z  Matt Brennan  Merge pull request #164 from Financial-Times/robots
7b84a64  2016-11-07T16:25:13Z  Matt Brennan  Add rollback section
683816a  2016-09-21T16:03:24Z  Matt Brennan  disallow non-article paths in crawler
7e43e11  2016-11-01T17:26:02Z  Matt Brennan  deployment …
```
> Change request AT-631

- views/ads-iframe.html
@andrewgeorgiou1981 @andygnewman @quarterto 
Add the undocumented magic line that makes Krux work (along with their fixed remote.min.js). ¯\_(ツ)_/¯
Tested locally and it was making the userdata call, and on subsequent requests sent the kuid and ksegs to the ad call.
> Implement Krux fix

- package.json
- server/lib/article/render-article.js
- server/lib/transforms/body.js
- test/fixtures/72402230-e6db-11e6-967b-c88452263daf.json
- test/integration/ads.js
- test/integration/index.js
- test/utils/chai.js
`enableAds` is required [here](https://github.com/Financial-Times/google-amp/blob/d87b8390af325546dddfba1af9b2da82ebddef16/server/lib/transforms/html/insert-ad.js#L9), but was being set all the way up [here](https://github.com/Financial-Times/google-amp/blob/d87b8390af325546dddfba1af9b2da82ebddef16/server/controllers/amp-page.js#L150) and wasn't making it through.
going to look if i can add an integration test for ads because we really should be catching this sooner.
> pass all options to transforms, fix AT-897

- server/lib/ammit.js
When calling Ammit, because Fastly has a vary limit for headers, we can't make use of CDN caching very efficiently. https://community.fastly.com/t/common-pitfalls-of-the-vary-header/370
In order to get better cache hit ratios, we move the allocation-id parameter from request header to the querystring.
> When calling Ammit, send the allocation id in the querystring

- app.js
- readme.md
- scripts/dev-utils/certificate.cnf
- server/index.js
Adds a redirect from http to https, and the `strict-transport-security` header.
This follows the HSTS policy we have on `www.ft.com`. I will follow this up by asking for `amp.ft.com`  to be added to the browser preload lists.
> HTTPS Only

- .circleci/config.yml
Add this project to next-webhooks.
Sound legit? Seem like a good idea?
My thoughts are it should help us generalise our tooling.
This will mean amp gets:
* Releases in #ft-next-releases
* Master branch failure notifications in a Slack direct message
> Notify next-webhooks on builds

- package.json
The semvar thing is quite npm specific.
We only really want to pin this anyway.
> Pin to o-date

- renovate.json
Reverts Financial-Times/google-amp#368.
After https://github.com/Financial-Times/google-amp/pull/369 was raised, I think it's wise for us to stick with preserving semver ranges on this project.
> Revert "Update Renovate"

- server/lib/transforms/html/link-analytics.js
- test/utils/test-uuids.js
The ops-cops ticket I'm working on:
https://trello.com/c/HTF2gdDM/569-amp-alphaville-issue
Google Search Consol started reporting 500 errors returning from our AMP app.
This fix only addresses alphaville related issues when href is not provided on an `<a>` element.
> Fix broken page when href not provided on a element

- server/lib/transforms/body.js
- server/lib/transforms/html/table.js
- test/amp-transform/table.js
This will convert the table into a link that goes to the article page.
The flat o-table style not behaving as it expected so
we will use this solution for the moment.
> Add table transformer

- package.json
- server/index.js
Release log was erroring because Konstructor didn't know about that email address any more :)
I think it makes sense for you still be listed as author and a contact, although we'll try and take over more when more work needs to be done?
> Update package author email and service contacts

- makefile
- test/smoke.js
n-gage has a bunch of smoke test behaviour that relies on http URLs in [review-app.mk](https://github.com/Financial-Times/n-gage/blob/v3.7.1/src/tasks/review-app.mk#L37) and [deploy.mk](https://github.com/Financial-Times/n-gage/blob/v3.7.1/src/tasks/deploy.mk#L75) .  Force https use to let these work with AMP staging URLs.
🐿 v2.12.3
> Force n-test smoke tests to use https

- views/layouts/layout.html
it should be top-level according to https://amp.dev/documentation/components/amp-subscriptions/#service-configuration. this should fix the symptoms of https://trello.com/c/vmKO5Qj1/1184-amp-barrier-for-content-that-should-be-free but not the root cause errors.
> move fallbackEntitlement outside of service configuration

- server/health/elastic-search.js
As part of the DNS migration from Dyn to Route53 the foundation services team are requesting us to move DNS records using Dyn's Traffic Management service under the glb.ft.com zone.
The next-elastic.glb.ft.com record is all setup to load balance DNS lookups, and resolves to the same records as next-elastic.ft.com.
Related change in n-es-client is https://github.com/Financial-Times/n-es-client/pull/41.
> feat: use next-elastic.glb.ft.com CNAME to connect to Elasticsearch

- secret-squirrel.js
- server/lib/article/assemble.js
this article has an image which should not be cached, but there's no way of not having google cache it, so remove the entire article from AMP.
see also financial-times/next-article#3606 and https://financialtimes.atlassian.net/browse/NOPSCOPS-27
> return 404 for the poll tracker article

- server/lib/article/article-flags.js
We had a similar issue trying to disable the swg button on the barriers. Handlebars is basically checking `{{#if "false"}}` and since it's a string it's truthy.
🐿 v2.12.3
> Fix check for env variable

- secret-squirrel.js
- server/controllers/amp-page.js
US delegate tracker contains a dynamic image which should not be cached
Related to https://github.com/Financial-Times/next-article/pull/3662
> Redirect US 2019 delegate tracker to FT.com

- server/lib/article/article-flags.js
- views/partials/barrier.html
- Conditionally show SWG buttons if `isReadyToPay` flag is `true`.
[Ticket](https://financialtimes.atlassian.net/browse/AC-49?atlOrigin=eyJpIjoiNTk3MTdlMGRjM2Q1NGNlM2I3ODg0MGJmODk3MTBkMDEiLCJwIjoiaiJ9)
> Add logic to only show the SWG button on `isReadyToPay` 🐿 v2.12.5

- secret-squirrel.js
- server/controllers/amp-page.js
Coronavirus tracker contains a dynamic image which should not be cached
Related to Financial-Times/next-article#3665
> Redirect coronavirus tracker to FT.com

- package-lock.json
- secret-squirrel.js
- server/controllers/amp-page.js
Removes the coronavirus economic tracker page from AMP (it contains a dynamic image that should not go through AMP)
Related to https://github.com/Financial-Times/next-article/pull/3741
> Remove coronavirus economic tracker from AMP 🐿 v2.12.5

- scss/_hacks.scss
There's a problem with images which contain transparency (PNGs, for example) when they're opened in light-boxes. Because light-boxes have a black background, they can make some images unreadable. It looks like this:
Whereas in actuality we'd like it to look like this:
Due to the unique way Amp transitions images into and out of light-boxes, it's not possible to just apply a background-color to `amp-lightbox-gallery img`. If you do, you get an ugly moment of black as the transition happens. It looks like this:
The solution is a hack which adds `background-color` to all images, regardless of whether they're in a light-box or undergoing transitions. Since there are no occasions where we don't display transparent images against a non-paper-coloured background, this shouldn't cause any damage.
> NOPS-COPS-36 Fix Transparent Images

- test/handlebars/express.test.js
Running `make test` would initialize the express app in `/utils/hbs-app/main'.js` before running all other tests and by the time it got to the handlebars tests it would start giving 500 errors
As a fix, I moved the initialization of the express app in `/utils/hbs-app/main'.js` to be right before the handlebars unit tests run.
> Fix for express-handlebars unit tests

- .circleci/config.yml
We've now added this to the shared Next folder in Vault so we can remove this todo :tada:
> Remove CircleCI todo from config

- package.json
This repo is still experiencing [failing CI workflows](https://app.circleci.com/pipelines/github/Financial-Times/google-amp/580/workflows/0efe0241-1bea-4ee3-a951-db0c8307635a/jobs/3934) as a result of the `No review app build found for app id` error that was fixed in https://github.com/Financial-Times/n-heroku-tools/pull/605/files and released as v10.0.1.
Major releases on `n-heroku-tools` since v8:
- **v9: Switch package engine from Node 8 to Node 10** - this repo is already on Node v12
- **v10: remove the `deploy-hashed-assets` command** - that command does not exist in this repo
- **v11: Upgrade to Node v14 + upload ICO files** - overshooting the mark; maybe the next release will bring it back down to a matching Node version…
- **v12: Use Node v12** - …ah, excellent 😄
> Upgrade n-heroku-tools ^8.1.3 -> ^12.1.0

- package.json
This PR changes the version of `n-es-client` to GitHub branch [`make-requests-to-next-elasticsearch-v7-gslb-ft-com`](https://github.com/Financial-Times/n-es-client/tree/make-requests-to-next-elasticsearch-v7-gslb-ft-com) so that all of its Elasticsearch requests are directed to the new Elasticsearch v7 cluster.
Once all apps that make Elasticsearch requests via `n-es-client` have been verified as working then a new major version of that package will be released and this PR updated to instead use that.
**Update:** `n-es-client` v3.0.0, which sends requests to the new Elasticsearch v7 cluster, has been released and this PR has been updated to consume that release.
> Upgrade n-es-client ^1.8.0 -> 3.0.0 (Elasticsearch v7 cluster)

- server/health/elastic-search.js
Part of the Elasticsearch migration.
This PR switches the healthcheck so instead of pointing at the soon-to-be retired v5 cluster it instead points to the now active v7 cluster.
> Switch healthcheck to Elasticsearch v7 cluster

- views/partials/header.html
Remove link to FastFT since it's now defunct.
See https://financialtimes.slack.com/archives/C03TWD9G1/p1621870002027800
[NOPS-48](https://financialtimes.atlassian.net/browse/NOPS-48)
> NOPS-48 remove link to FastFT since it's now defunct.

- .circleci/config.yml
- .github/settings.yml
- package.json
- readme.md
- renovate.json
- server/controllers/analytics-proxy.js
- server/lib/transforms/html/remove-invalid-links.js
bonus discovery that `masterIssue`  isn't a thing in renovate anymore, it's called `dependencyDashboard` as per the [release notes.](https://github.com/renovatebot/renovate/pull/6729/files)
> Master to main

- vcl/main.vcl
The value of fastly-client-ip is not protected from modification at the edge of the Fastly network,
so if a client sets this header themselves, it will be used.
To protect against this we set it ourselves.
https://developer.fastly.com/reference/http/http-headers/Fastly-Client-IP/
This service and app doesn't actually use this header at the moment but I am adding this protection just incase it is used in the future.
> Set fastly-client-ip on the edge

- package.json
See https://response.ftops.tech/incident/1380/
on 8th Jan, v1.4.1 of colors.js was released, which deliberately causes an infinite loop when the package is used
this causes CircleCI builds for affected services to run indefinitely. Pinning colors to v1.4.0, which is the last known good version, circumvents the issue.
In the case of AMP colors is somewhere down in the dependency tree. Pinning the version in package.json installs the correct version and AMP continues to display correctly when run locally.
> CI-976 Pin colors to v1.4.0 to avoid known vulnerability in colors v1.4.1

- vcl/main.vcl
The old dataset is looking to be retired soon - approximately May 2022
The data returned for a given IP address may be different between the current and legacy datasets, especially at the city level.
The other differences between the two datasets are:
Results for IPv6 addresses are only returned in the new dataset.
The datasets each have different formatting conventions. For example, `client.geo.city` and `client.geo.country_name` exist as lowercase ASCII values whereas the values returned for the same fields in the `geoip.` namespace are mixed case.
The `client.geo.region` field contains ISO 3166-2 region codes but the `geoip.region` field contains FIPS10-4 region codes. 
More documentation about this can be found at https://developer.fastly.com/reference/vcl/variables/geolocation/
> move from legacy dataset available under geoip to the current dataset under client.geo

- package.json
- server/controllers/amp-page.js
- server/index.js
As a part of the plan to disable AMP on FT, this PR is to toggle the re-direct of AMP page requests based on a flag `redirectAmpPageTemp`. When the flag is on, instead of providing the AMP version of the content page, it sends a `302 Found` to redirect the request to the canonical FT.com page.
> ADSDEV-1055 Create AMP re-direct
